package br.com.view;

import br.com.kahoot.dao.AssuntoDao;
import br.com.kahoot.dao.PerguntaDao;
import br.com.kahoot.daoimpl.AssuntoDaoImpl;
import br.com.kahoot.daoimpl.PerguntaDaoImpl;
import br.com.kahoot.entidade.Assunto;
import br.com.principal.Principal;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class CadastroPerguntaPanel extends javax.swing.JPanel {

    private PerguntaDao PERGUNTA_DAO = new PerguntaDaoImpl();
    private AssuntoDao ASSUNTO_DAO = new AssuntoDaoImpl();

    /**
     * Creates new form CadastroPerguntaPanel
     */
    public CadastroPerguntaPanel() throws Exception {
        initComponents();
        /**
         * Listando os assuntos na combobox
         */
        ListarComboBox();
    }

    public void ListarComboBox() throws Exception {
        MostrandoListaAssunto();
    }

    public void MostrandoListaAssunto() throws Exception {
        try {
            List<?> assuntos = ASSUNTO_DAO.pesquisarTodos();
            List<Assunto> assunto = (List<Assunto>) (Object) assuntos;
            for (Assunto ass : assunto) {
                ComboAssunto.addItem(ass.getNome());
            }
        } catch (SQLException ex) {
            System.out.println(ex.getStackTrace());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CampoPergunta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BotaoVoltar = new javax.swing.JButton();
        BotaoGravar = new javax.swing.JButton();
        ComboAssunto = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CampoResposta1 = new javax.swing.JTextField();
        CampoResposta2 = new javax.swing.JTextField();
        CampoResposta3 = new javax.swing.JTextField();
        CampoResposta4 = new javax.swing.JTextField();
        BotaoResposta1 = new javax.swing.JRadioButton();
        BotaoResposta2 = new javax.swing.JRadioButton();
        BotaoResposta3 = new javax.swing.JRadioButton();
        BotaoResposta4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setText("CADASTRO PERGUNTA");
        jPanel1.add(jLabel3, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        CampoPergunta.setColumns(30);
        CampoPergunta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(CampoPergunta, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("PERGUNTA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel2.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        BotaoVoltar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotaoVoltar.setText("VOLTAR");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });
        jPanel3.add(BotaoVoltar, new java.awt.GridBagConstraints());

        BotaoGravar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotaoGravar.setText("GRAVAR");
        BotaoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGravarActionPerformed(evt);
            }
        });
        jPanel3.add(BotaoGravar, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jPanel3, gridBagConstraints);

        ComboAssunto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ComboAssunto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Assunto" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(ComboAssunto, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("RESPOSTAS"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Resposta 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel4.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Resposta 2:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel4.add(jLabel2, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Resposta 3:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel4.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Resposta 4;");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel4.add(jLabel6, gridBagConstraints);

        CampoResposta1.setColumns(30);
        CampoResposta1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel4.add(CampoResposta1, gridBagConstraints);

        CampoResposta2.setColumns(30);
        CampoResposta2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel4.add(CampoResposta2, gridBagConstraints);

        CampoResposta3.setColumns(30);
        CampoResposta3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel4.add(CampoResposta3, gridBagConstraints);

        CampoResposta4.setColumns(30);
        CampoResposta4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel4.add(CampoResposta4, gridBagConstraints);

        BotaoResposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoResposta1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel4.add(BotaoResposta1, gridBagConstraints);

        BotaoResposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoResposta2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel4.add(BotaoResposta2, gridBagConstraints);

        BotaoResposta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoResposta3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel4.add(BotaoResposta3, gridBagConstraints);

        BotaoResposta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoResposta4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel4.add(BotaoResposta4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        add(jPanel4, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Desenvolvido por Agostinho, Adriene, kellison, William");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jLabel7, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        /**
         * Volta para o menu do projeto
         */
        Principal.panelMenu();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGravarActionPerformed
        /**
         * Verificando se os campos foram preenchidos corretamente
         */
        if (CampoPergunta.getText().isEmpty()
                || CampoResposta1.getText().isEmpty()
                || CampoResposta2.getText().isEmpty()
                || CampoResposta3.getText().isEmpty()
                || CampoResposta4.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos para prosseguir!");
            /**
             *
             */
        } else {

        }

    }//GEN-LAST:event_BotaoGravarActionPerformed

    private void BotaoResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoResposta1ActionPerformed
        /**
         * Verificando se o usuario marcar o primeiro botao o resto se torna
         * Imarcável
         */
        if (BotaoResposta1.isSelected()) {
            BotaoResposta2.setSelected(false);
            BotaoResposta3.setSelected(false);
            BotaoResposta4.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoResposta1ActionPerformed

    private void BotaoResposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoResposta2ActionPerformed
        /**
         * Verificando se o usuario marcar o segundo botao o resto se torna
         * Imarcável
         */
        if (BotaoResposta2.isSelected()) {
            BotaoResposta1.setSelected(false);
            BotaoResposta3.setSelected(false);
            BotaoResposta4.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoResposta2ActionPerformed

    private void BotaoResposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoResposta3ActionPerformed
        /**
         * Verificando se o usuario marcar o terceiro botao o resto se torna
         * Imarcável
         */
        if (BotaoResposta3.isSelected()) {
            BotaoResposta1.setSelected(false);
            BotaoResposta2.setSelected(false);
            BotaoResposta4.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoResposta3ActionPerformed

    private void BotaoResposta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoResposta4ActionPerformed
        /**
         * Verificando se o usuario marcar o quarto botao o resto se torna
         * Imarcável
         */
        if (BotaoResposta4.isSelected()) {
            BotaoResposta1.setSelected(false);
            BotaoResposta2.setSelected(false);
            BotaoResposta3.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoResposta4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGravar;
    private javax.swing.JRadioButton BotaoResposta1;
    private javax.swing.JRadioButton BotaoResposta2;
    private javax.swing.JRadioButton BotaoResposta3;
    private javax.swing.JRadioButton BotaoResposta4;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField CampoPergunta;
    private javax.swing.JTextField CampoResposta1;
    private javax.swing.JTextField CampoResposta2;
    private javax.swing.JTextField CampoResposta3;
    private javax.swing.JTextField CampoResposta4;
    private javax.swing.JComboBox<String> ComboAssunto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
