package br.com.view;

import br.com.kahoot.dao.DisciplinaDao;
import br.com.kahoot.daoimpl.DisciplinaDaoImpl;
import br.com.kahoot.entidade.Disciplina;
import br.com.principal.Principal;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class CadastroDisciplinaPanel extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarDisciplina
     */
    public CadastroDisciplinaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        textoNome = new javax.swing.JLabel();
        textoProfessor = new javax.swing.JLabel();
        CampoNomeDisciplina = new javax.swing.JTextField();
        CampoProfessor = new javax.swing.JTextField();
        PanelBotaoInferior = new javax.swing.JPanel();
        BotaoVoltar = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        PanelFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoDesenvolvimento = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        textoNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textoNome.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(textoNome, gridBagConstraints);

        textoProfessor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textoProfessor.setText("Professor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(textoProfessor, gridBagConstraints);

        CampoNomeDisciplina.setColumns(30);
        CampoNomeDisciplina.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(CampoNomeDisciplina, gridBagConstraints);

        CampoProfessor.setColumns(30);
        CampoProfessor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(CampoProfessor, gridBagConstraints);

        PanelBotaoInferior.setLayout(new java.awt.GridBagLayout());

        BotaoVoltar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotaoVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_voltar_32x32.png"))); // NOI18N
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 16);
        PanelBotaoInferior.add(BotaoVoltar, gridBagConstraints);

        BotaoSalvar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salvar_32x32.png"))); // NOI18N
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        PanelBotaoInferior.add(BotaoSalvar, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(PanelBotaoInferior, gridBagConstraints);

        PanelFundo.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("CADASTRO DISCIPLINA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        PanelFundo.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(PanelFundo, gridBagConstraints);

        textoDesenvolvimento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        textoDesenvolvimento.setText("Desenvolvido por Agostinho, Adriene, kellison, William");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(textoDesenvolvimento, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        Principal.panelMenu();

        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        /**
         * Recebendo da Inteface e salvando Disciplina no Banco de dados.
         */
        salvandoDisciplina();
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    public void salvandoDisciplina() throws HeadlessException {
        if (CampoNomeDisciplina.getText().isEmpty() || CampoProfessor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor preencha os campos para prosseguir");
        } else {
            /**
             * Criando Objeto Disciplina.
             */
            Disciplina disciplina = criandoDisciplina();
            /**
             * Gravando Disciplina no banco de dados através do DisciplinaDao.
             *
             */

            gravandoDisciplinaNoBanco(disciplina);
        }
    }

    public void gravandoDisciplinaNoBanco(Disciplina disciplina) throws HeadlessException {
        DisciplinaDao disciplinaDao = new DisciplinaDaoImpl();

        try {
            Boolean tudoOk = disciplinaDao.inserir(disciplina);
            if (tudoOk) {
                JOptionPane.showMessageDialog(null, "Disciplina inserida com sucesso!");
                disciplina.setNome(null);
                disciplina.setProfessor(null);
                Principal.panelCadastroDisciplina();
            } else {
                JOptionPane.showMessageDialog(null, "Problemas ao cadastrar disciplina!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Problema com banco Verificar!!");
        }
    }

    public Disciplina criandoDisciplina() {
        Disciplina disciplina = new Disciplina();
        disciplina.setNome(CampoNomeDisciplina.getText());
        disciplina.setProfessor(CampoProfessor.getText());
        return disciplina;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField CampoNomeDisciplina;
    private javax.swing.JTextField CampoProfessor;
    private javax.swing.JPanel PanelBotaoInferior;
    private javax.swing.JPanel PanelFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textoDesenvolvimento;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoProfessor;
    // End of variables declaration//GEN-END:variables
}
