package br.com.view;

import br.com.kahoot.dao.DisciplinaDao;
import br.com.kahoot.daoimpl.DisciplinaDaoImpl;
import br.com.kahoot.entidade.Disciplina;
import br.com.principal.Principal;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class CadastroDisciplinaPanel extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarDisciplina
     */
    public CadastroDisciplinaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoNomeDisciplina = new javax.swing.JTextField();
        CampoProfessor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BotaoVoltar = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Professor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jLabel3, gridBagConstraints);

        CampoNomeDisciplina.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(CampoNomeDisciplina, gridBagConstraints);

        CampoProfessor.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(CampoProfessor, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        BotaoVoltar.setText("VOLTAR");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(BotaoVoltar, new java.awt.GridBagConstraints());

        BotaoSalvar.setText("SALVAR");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BotaoSalvar, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setText("CADASTRO DISCIPLINA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        Principal.panelMenu();

        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        /**
         * Recebendo da Inteface e salvando Disciplina no Banco de dados.
         */
        salvandoDisciplina();
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    public void salvandoDisciplina() throws HeadlessException {
        if (CampoNomeDisciplina.getText().isEmpty() || CampoProfessor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor preencha os campos para prosseguir");
        } else {
            /**
             * Criando Objeto Disciplina.
             */
            Disciplina disciplina = criandoDisciplina();
            /**
             * Gravando Disciplina no banco de dados através do DisciplinaDao.
             *
             */

            gravandoDisciplinaNoBanco(disciplina);
        }
    }

    public void gravandoDisciplinaNoBanco(Disciplina disciplina) throws HeadlessException {
        DisciplinaDao disciplinaDao = new DisciplinaDaoImpl();

        try {
            Boolean tudoOk = disciplinaDao.inserir(disciplina);
            if (tudoOk) {
                JOptionPane.showMessageDialog(null, "Disciplina inserida com sucesso!");
                disciplina.setNome(null);
                disciplina.setProfessor(null);
                Principal.panelCadastroDisciplina();
            } else {
                JOptionPane.showMessageDialog(null, "Problemas ao cadastrar disciplina!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Problema com banco Verificar!!");
        }
    }

    public Disciplina criandoDisciplina() {
        Disciplina disciplina = new Disciplina();
        disciplina.setNome(CampoNomeDisciplina.getText());
        disciplina.setProfessor(CampoProfessor.getText());
        return disciplina;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField CampoNomeDisciplina;
    private javax.swing.JTextField CampoProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
